android_library(
  name = 'src',
  srcs = glob(['src/main/java/**/*.java']),
  deps = ['//rebound-core:src'],
  visibility = ['PUBLIC'],
)

project_config(
  src_target = '//rebound-android:src',
  src_roots = ['src/main/java'],
)
